config/routes.rb
Games::Application.routes.draw do
 
    resources :developers do
        resources :games, shallow: true
        end
    
    get '/games', to: 'games#all'

    root 'welcome#index'
    

end

app/models/developer.rb
class Developer < ActiveRecord::Base
    has_many :games,  dependent: :destroy
    validates :name, presence: true               
end

app/models/game.rb
class Game < ActiveRecord::Base
    belongs_to :developer
    validates :name, presence: true
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/developers_controller.rb
class DevelopersController < ApplicationController
    
    before_action :get_developer, only: [:show, :delete, :edit, :update, :destroy]
    http_basic_authenticate_with name: "admin", password: "admin", except: [:index, :show]
    
    def index
        @developers = Developer.all
    end   
    
    def new 
        @developer = Developer.new
    end
    
    def create
        @developer = Developer.new(developer_params)
        @developer.formed = Time.new
        if (@developer.save)
            redirect_to @developer
        else
            render 'new'
        end
    end
    
    def update 
        if(@developer.update(developer_params))
            redirect_to @developer
        else
            render 'edit'
        end
    end   
    
    def destroy
        @developer.destroy
        redirect_to games_path
    end
    
    private
    def developer_params
        params.require(:developer).permit(:name)
    end
    
    private
    def get_developer
        @developer = Developer.find(params[:id])
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

    before_action :get_game, only: [:show, :delete, :edit, :update, :destroy]
    http_basic_authenticate_with name: "admin", password: "admin", except: [:index, :show]

    def all
        @games = Game.all 
    end
    
    def index
        @developer = Developer.find(params[:developer_id])
        @games = @developer.games
    end

    def new
        @developer = Developer.find(params[:developer_id])
        @game = @developer.games.new
    end

    def create
        @developer = Developer.find(params[:developer_id])
        @game = @developer.games.create(game_params)
        @game.released = Time.new
        if(@game.save)
           redirect_to @game.developer
        else
            render 'new'
        end
    end

    def update
        if(@game.update(game_params))
            redirect_to @game.developer
        else
            render 'edit'
        end
    end
    
    def destroy 
        developer = @game.developer
        @game.destroy
        redirect_to @game.developer
    end


    private 
    def game_params
        params.require(:game).permit(:name, :description)
    end

    private 
    def get_game
        @game = Game.find(params[:id])
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/developers_helper.rb
module DevelopersHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/developers/_form.html.erb
<%= form_for @developer do |f| %>
<p>    
    <%= f.label :name %>
    <%= f.text_field :name %>
    
</p> 

<p>
    <%= f.submit %>
</p>

<% end %>

app/views/developers/edit.html.erb
<h2>Edit developer</h2>

<%= render 'form' %>

app/views/developers/index.html.erb
<h2>Developer Index</h2>

<%= link_to 'Create Developer', new_developer_path %>

<table>
    <tr>
        <th>Name</th>
        <th>Formed</th>

    
    </tr>
    <% @developers.each do |dev| %>
        <tr>
            <td><%= link_to  dev.name, dev %></td>
            <td><%= dev.formed %></td>  
            <td> <%= link_to 'Edit', edit_developer_path(dev) %>
                    <%= link_to 'Delete', dev, method: :delete, data: { confirm: 'Are you sure?' } %> 
            </td>
    
        </tr>
    <% end %>
    
   
</table>
 <% if @developers.count == 0%>
        <p>No Developers found</p>
<% end %>

app/views/developers/new.html.erb
<h2>New developer</h2>

<%= render 'form' %>

app/views/developers/show.html.erb
<h2><%= @developer.name %></h2>

<b>Formed: </b> <%= @developer.formed %>

<h3>Games:</h3>
<table>
    <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Released</th>
    
    </tr>
    <% @developer.games.each do |game| %>
        <tr>
            <td><%= game.name %></td>
            <td><%= game.description %></td>  
            <td><%= game.released %></td>
            <td> <%= link_to 'Edit', edit_game_path( game) %>
                    <%= link_to 'Delete', [game], method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>

    
        </tr>
    <% end %>

</table>

  <% if @developer.games.count == 0 %>
        <p>No games</p>
    <% end %>

<%= link_to 'Add game', new_developer_game_path(@developer) %>

app/views/games/_edit_form.html.erb
<%= form_for(@game) do |f| %>

<p>
    <%= f.label :name %> <br>
    <%= f.text_field :name %>
</p>

<p>
    <%= f.label :description %> <br>
    <%= f.text_area :description %>

</p>

<p>
    <%= f.submit %>
</p>


<% end %>

app/views/games/_form.html.erb
<% if @game.errors.any? %>

<h3>Errors have prevented this game from being saved:</h3> <br>
    
    <% @game.errors.full_messages.each do |msg| %>
        <%= msg %> <br>
    <% end %>

<% end %>

<%= form_for([@developer, @developer.games.build]) do |f| %>
   <p>
    <%= f.label :name %> <br>
    <%= f.text_field :name %>
</p>

<p>
    <%= f.label :description %> <br>
    <%= f.text_area :description %>

</p>

<p>
    <%= f.submit %>
</p>
<% end %>

app/views/games/_form_fields.html.erb
<p>
    <%= f.label :name %> <br>
    <%= f.text_field :name %>
</p>

<p>
    <%= f.label :description %> <br>
    <%= f.text_area :description %>

</p>

<p>
    <%= f.submit %>
</p>

app/views/games/_game.html.erb
<p>
    <b>Title: </b> <%= @game.name %>
</p>

<p>
    <b>Description: </b> <%= @game.description %>
</p>

<p>
    <b>Released: </b> <%= @game.released %>
</p>

app/views/games/all.html.erb
<h1>Games List</h1>

<table>
    <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Released</th>
        <th>Developer</th>
    
    </tr>
    <% @games.each do |game| %>
        <tr>
            <td><%= link_to  game.name, game %></td>
            <td><%= game.description %></td>  
            <td><%= game.released %></td>
            <td><%= game.developer.name %> </td>
            <td> <%= link_to 'Edit', edit_game_path(game) %>
                    <%= link_to 'Delete', game, method: :delete, data: { confirm: 'Are you sure?' } %> 
            </td>
    
        </tr>
    <% end %>
</table>

app/views/games/edit.html.erb
<h2>Edit Game Details</h2>

<%= render 'edit_form' %>

app/views/games/index.html.erb
<h2>Games Index</h2>


<%= link_to 'Create new game', new_game_path %> <br>

<table>
    <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Released</th>
    
    </tr>
    <% @games.each do |game| %>
        <tr>
            <td><%= link_to  game.name, game %></td>
            <td><%= game.description %></td>  
            <td><%= game.released %></td>
            <td> <%= link_to 'Edit', edit_game_path(game) %>
                    <%= link_to 'Delete', game, method: :delete, data: { confirm: 'Are you sure?' } %> 
            </td>
    
        </tr>
    <% end %>
</table>

<% if @games.count == 0 %>
    <p>No games found</p>
<% end %>

app/views/games/new.html.erb
<h2>Create new game</h2>

<%= render 'form' %>

<%= link_to 'Back', developer_games_path(@developer) %>

app/views/games/show.html.erb
<h2>Game Details</h2>

<%= render 'game' %>

<%= link_to 'Edit this game', edit_game_path(@game) %>
<%= link_to 'Delete', [@game], method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to 'Back to developer' , @developer %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Games</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <h1>Rails test application</h1>
    <%= link_to 'Home', root_path %>
    <br>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h2>Index</h2>

<%= link_to 'View Developers', developers_path %>